// Bundles src/runtime/iframe-entry.tsx into a single, dependency-free
// browser IIFE (React + ReactDOM + jsx-runtime inlined) and writes the
// result as a TypeScript string-literal module. That module is imported
// by src/view/MdxPreviewView.ts and its contents are written into the
// sandboxed iframe's srcdoc as a literal <script> tag — no network
// fetch, no eval, no new Function.
import * as esbuild from "esbuild";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

const result = await esbuild.build({
	entryPoints: [path.join(root, "src/runtime/iframe-entry.tsx")],
	bundle: true,
	write: false,
	format: "iife",
	platform: "browser",
	target: "es2020",
	minify: process.env.NODE_ENV === "production",
	jsx: "automatic",
	logLevel: "info",
});

const js = result.outputFiles[0].text;

const outPath = path.join(root, "src/runtime/iframeRuntimeSource.generated.ts");
const banner = `// AUTO-GENERATED by scripts/build-runtime.mjs — do not edit by hand.\n// Regenerate with \`npm run build:runtime\`.\n\n`;
const body = `export const IFRAME_RUNTIME_JS: string = ${JSON.stringify(js)};\n`;

writeFileSync(outPath, banner + body, "utf8");
console.log(`[build-runtime] wrote ${outPath} (${(js.length / 1024).toFixed(1)} KB)`);
